### ISSUE TITLE
Проверка дз 1

### ISSUE THREAD

**Issue by LilyKras** [qwert21ant/tododo#2]
**Чистота кода и общая структура проекта 4/4**

Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов 1/1  все есть

Форматирование кода присутствует 1/1 

Код разбит на фичи и слои (не важно, feature-first / layer-first) 2/2

**Вёрстка + навигация 16/16**

Полностью свёрстаны 2 экрана по макетам: основной и добавления/редактирования задачи 10/10
Но пару замечаний:
- следует убрать возможность сохранять пустые заметки
 ![image](https://i.ibb.co/DMyNc0L/IMG-5580-2.jpg) 

- в дизайне у Новое больше нижний паддинг
 ![image](https://i.ibb.co/Qmpdtqk/IMG-5580-3.jpg) 

- иконка глаза должна быть на одном уровне с выполнено
![image](https://i.ibb.co/xDx5XV9/IMG-5580.jpg) 

Свайп по айтему Выполнено/Удалить с логикой 3/3
Очень круто! 

Показ выполненных дел с логикой 3/3
Все хорошо 

**Разное** 

Реализовано нормальное логирование (не print'ы) 
Не нашла, можешь подсказать, где?

Есть человеческая иконка у приложения (iOS или Android) 
Иконка есть и прикольная 4/4

**Comment by qwert21ant** [comment]
Логгер: /lib/utils/logger.dart

**Comment by LilyKras** [comment]
нашла, спасибо)
